config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  draw(:admin)

  resources :products, only: :show
  resources :diaries
  resource :cart, only: :show do
    resources :cart_items, only: %i[create destroy]
  end
  resources :orders, only: %i[index show create]
  resources :shipping_addresses

  get 'up' => 'rails/health#show', as: :rails_health_check
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_carts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Cart < ApplicationRecord
  include TaxCalculable

  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  TAX_RATE = 1.08
  SHIPPING_COST = 600

  COD_FEE = {
    0..9_999 => Money.new(300),
    10_000..29_999 => Money.new(400),
    30_000..99_999 => Money.new(600),
    100_000..Float::INFINITY => Money.new(1_000),
  }.freeze

  def subtotal_price
    Money.new(cart_items.preload(:product).sum { _1.product.price.cents })
  end

  def total_price_with_tax
    subtotal_price * TAX_RATE
  end

  def shipping_fee
    if cart_items.size <= 5
      Money.new(SHIPPING_COST)
    else
      additional_units = ((cart_items.size - 5).to_f / 5).ceil
      Money.new(SHIPPING_COST + (additional_units * SHIPPING_COST))
    end
  end

  def cod_fee
    COD_FEE.find { |key, _| key.cover?(subtotal_price.cents) }&.last || Money.new(0)
  end

  def total_price
    (subtotal_price * TAX_RATE) + shipping_fee + cod_fee
  end

  def order!
    order = user.orders.new

    transaction do
      add_order_items_to_order(order)
      if order.order_items.present?
        order.price = self.total_price
        order.save!
        OrderMailer.order_confirmation(order).deliver_later
        cart_items.destroy_all
      end
    end
  end

  private

  def add_order_items_to_order(order)
    cart_items.eager_load(:product).each do |cart_item|
      order.order_items.new(product: cart_item.product, price: cart_item.product.price)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
  end
end

app/views/carts/show.html.haml
.container.mt-4
  .row.g-4
    %section.col-md-8
      - if @cart.cart_items.present?
        -# #TODO - viewにロジックを持ちたくない
        - @cart.cart_items.default_order.preload(product: { image_attachment: :blob }).each do |cart_item|
          .card.mb-3.shadow-sm.border-0
            .row.g-0.align-items-center
              .col-md-3.p-3
                - if cart_item.product.image.attached?
                  = image_tag(cart_item.product.image.variant(:thumbnail), class: 'img-fluid rounded', alt: "#{cart_item.product.name} の表紙")
                - else
                  = image_tag 'no_image.png', class: 'img-fluid rounded', alt: '画像なし'
              .col-md-9
                .card-body.d-flex.flex-column
                  %h2.card-title
                    = link_to cart_item.product.name, product_path(cart_item.product), class: 'text-decoration-none text-dark'
                  %p.card-text.mt-2
                    %span.text-dark #{cart_item.product.price_with_tax.format}(税込)
                  = button_to '削除', cart_cart_item_path(cart_item), method: :delete, class: 'btn text-primary', data: { turbo_confirm: 'カートから削除しますか？' }

      - else
        .text-center.py-5.mx-auto.col-md-10
          %i.bi.bi-cart.fs-1.text-muted.mb-3.d-block
          %h2 カートに商品が入っていません
          %p.text-muted 商品を追加してお買い物をお楽しみください
          = link_to '商品一覧へ', root_path, class: 'btn btn-primary'

    - if @cart.cart_items.present?
      %section.col-md-4
        .card.shadow-sm.border-0.p-3
          .d-flex.align-items-center.justify-content-between.w-100.border-bottom.pb-2.mb-2
            %span 小計(税込):
            %span.text-end= @cart.total_price_with_tax.format
          .d-flex.align-items-center.justify-content-between.w-100.border-bottom.pb-2.mb-2
            %span 送料:
            %span.text-end= @cart.shipping_fee.format
          .d-flex.align-items-center.justify-content-between.w-100.border-bottom.pb-2.mb-2
            %span 代引き決済手数料:
            %span.text-end= @cart.cod_fee.format
          .d-flex.align-items-center.justify-content-between.w-100.pb-2.fw-bold
            %span 合計:
            -# #TODO - 税金計算は後で実装
            %span= @cart.total_price.format
          = button_to orders_path, class: 'btn btn-primary btn-lg w-100 rounded-3 shadow-sm mt-3', data: { turbo_confirm: '注文を確定してもよろしいですか?' } do
            %i.bi.bi-cart-check.me-2
            %span 購入する