config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  draw(:admin)

  resources :products, only: :show
  resources :diaries
  resource :cart, only: :show do
    resources :cart_items, only: %i[create destroy]
  end
  resources :orders, only: %i[index show create]
  resources :shipping_addresses

  get 'up' => 'rails/health#show', as: :rails_health_check
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController
  before_action :set_shipping_address, only: %i[edit update destroy]

  def index
    @shipping_addresses = current_user.shipping_addresses.default_order
  end

  def new
    @shipping_address = current_user.shipping_addresses.new
  end

  def edit
  end

  def create
    @shipping_address = current_user.shipping_addresses.new(shipping_address_params)
    if @shipping_address.save
      redirect_to shipping_addresses_path, notice: '配送先住所を登録しました'
    else
      render :new, status: :unprocessable_entity, notice: '配送先住所の登録に失敗しました'
    end
  end

  def update
    if @shipping_address.update(shipping_address_params)
      redirect_to shipping_addresses_path, notice: '配送先住所を更新しました'
    else
      render :edit, status: :unprocessable_entity, notice: '更新に失敗しました'
    end
  end

  def destroy
    @shipping_address.destroy!

    redirect_to shipping_addresses_path, status: :see_other, notice: '配送先住所を削除しました'
  end

  private

  def set_shipping_address
    @shipping_address = current_user.shipping_addresses.find(params.expect(:id))
  end

  def shipping_address_params
    params.expect(shipping_address: %i[recipient_name postal_code prefecture_id city street_address])
  end
end

app/views/shipping_addresses/_form.html.haml
= simple_form_for([shipping_address]) do |form|
  = form.input :recipient_name, required: true, input_html: { autocomplete: 'recipient_name' }
  = form.input :postal_code, required: true, input_html: { autocomplete: 'postal_code' }
  = form.input :prefecture_id, collection: Prefecture.all.map { |p| [p.name, p.id] }, prompt: '選択してください'
  = form.input :city, required: true, input_html: { autocomplete: 'address' }
  = form.input :street_address, input_html: { autocomplete: 'address', placeholder: '例: ○○○マンション101号' }
  = form.submit class: 'btn btn-primary'

app/views/shipping_addresses/edit.html.haml
%h1.fs-4 配送先住所編集
= render 'form', shipping_address: @shipping_address

app/views/shipping_addresses/index.html.haml
%h1.fs-4 配送先住所一覧

= link_to '新しいお届け先住所を登録', new_shipping_address_path, class: 'nav-link text-primary'

- @shipping_addresses.each do |shipping_address|
  .mt-2.card
    .card-body
      .card-title.fw-bold= shipping_address.recipient_name
      .card-text #{shipping_address.postal_code} #{shipping_address.prefecture.name} #{shipping_address.city}
      %div
        = link_to '配送先を編集する', edit_shipping_address_path(shipping_address), class: 'nav-link text-primary'
        = button_to '配送先を削除する', shipping_address, method: :delete, data: { turbo_confirm: '本当に削除しますか？' }, class: 'nav-link text-black'

app/views/shipping_addresses/new.html.haml
%h1.fs-4 新しいお届け先住所を入力
= render 'form', shipping_address: @shipping_address