config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  draw(:admin)

  resources :products, only: :show
  resources :diaries
  resource :cart, only: :show do
    resources :cart_items, only: %i[create destroy]
  end
  resources :orders, only: %i[index show create]
  resources :shipping_addresses

  get 'up' => 'rails/health#show', as: :rails_health_check
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id             :bigint           not null, primary key
#  description    :text             default(""), not null
#  name           :string           not null
#  price_cents    :integer
#  price_currency :string           default("JPY"), not null
#  published      :boolean          default(FALSE), not null
#  row_order      :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Product < ApplicationRecord
  include RankedModel
  include TaxCalculable

  ranks :row_order

  has_one_attached :image do |attachable|
    attachable.variant :thumbnail, resize_to_limit: [600, 600]
    attachable.variant :icon, resize_to_fit: [50, 50]
  end
  has_many :cart_items, dependent: :destroy

  ACCEPTED_CONTENT_TYPES = %w[image/png image/jpeg image/gif image/tiff].freeze

  monetize :price_cents, allow_nil: true, numericality: { greater_than_or_equal_to: 0, message: 'は0以上の値にしてください' }

  validates :name, presence: true
  validates :image, content_type: ACCEPTED_CONTENT_TYPES, size: { less_than: 25.megabytes }
  validates :row_order_position, numericality: { only_integer: true }, allow_nil: true
  with_options if: :published? do
    validates :name, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0, message: 'は0以上の値にしてください' }
    validates :description, presence: true
    validate :image_attached
  end

  scope :default_order, -> { order(created_at: :desc, id: :desc) }
  scope :sorted_by_rank, -> { rank(:row_order) }
  scope :published, -> { where(published: true) }

  private

  def image_attached
    errors.add(:image, 'を添付してください') unless image.attached?
  end
end

app/controllers/admins/products/positions_controller.rb
class Admins::Products::PositionsController < Admins::ApplicationController
  def update
    product = Product.find(params.expect(:product_id))

    product.update!(row_order_position: params.expect(:row_order_position))
  end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @pagy, @products = pagy(Product.default_order)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admins_products_path, notice: '商品を登録しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      redirect_to admins_product_path(@product), notice: '商品を更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy!

    redirect_to admins_products_path, status: :see_other, notice: '商品を削除しました'
  end

  private

  def set_product
    @product = Product.find(params.expect(:id))
  end

  def product_params
    params.expect(product: %i[name price description image published])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @pagy, @products = pagy(Product.published.preload(image_attachment: :blob).sorted_by_rank.default_order)
  end

  def show
    @product = Product.find(params.expect(:id))
  end
end

app/views/products/index.html.haml
.container
  .row
    - @products.each do |product|
      .col-md-4.mt-4
        .card
          .card-img-container.p-3
            - if product.image.attached?
              = image_tag product.image.variant(:thumbnail), class: 'card-img-top img-fit-contain'
            - else
              = image_tag 'no_image.png', class: 'card-img-top bg-light img-fit-contain'
          .card-body.pt-2
            = link_to product.name, product_path(product), class: 'text-decoration-none'

  .mt-4
    != pagy_bootstrap_nav(@pagy)

app/views/products/show.html.haml
.container.mt-5
  .row
    .col-md-5
      .product-image.mt-4
        - if @product.image.attached?
          = image_tag @product.image.variant(:thumbnail), class: 'img-fluid rounded img-fit-contain'
        - else
          = image_tag 'no_image.png', class: 'img-fluid rounded bg-light img-fit-contain'

    .col-md-7
      %h2.mt-3.fw-bold= @product.name
      .text-dark.fs-4= @product.price.format

      .card.shadow-sm.mt-4
        .card-body
          %h3.card-title.border-bottom.pb-2 商品説明
          %p.card-text.mt-3= @product.description

      - if user_signed_in?
        .d-grid.gap-2.mt-4
          = button_to 'カートに追加', cart_cart_items_path(product_id: @product.id), class: 'btn btn-primary btn-lg fw-bold'